config/routes.rb
TreeNavExperiment::Application.routes.draw do  root to: "pages#index"
  resources "pages"

  root to: "pages#index"

end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :parent_id, :content, :name

  before_destroy :move_orphans

  has_ancestry orphan_strategy: :restrict

  def move_orphans
    unless self.class.orphan_strategy == :adopt
      descendants.all.each do |descendant|
        descendant.without_ancestry_callbacks do
          new_ancestry = descendant.ancestor_ids.delete_if { |x| x == self.id }.join("/")
          descendant.update_attribute descendant.class.ancestry_column, new_ancestry || nil
        end
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.arrange

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pages }
    end
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
    @page = Page.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @page }
    end
  end

  # GET /pages/new
  # GET /pages/new.json
  def new
    @page = Page.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @page }
    end
  end

  # GET /pages/1/edit
  def edit
    @page = Page.find(params[:id])
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(params[:page])

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render json: @page, status: :created, location: @page }
      else
        format.html { render action: "new" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pages/1
  # PUT /pages/1.json
  def update
    @page = Page.find(params[:id])

    respond_to do |format|
      if @page.update_attributes(params[:page])
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page = Page.find(params[:id])
    @page.destroy

    respond_to do |format|
      format.html { redirect_to pages_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title TreeNavExperiment
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          = link_to "Tree Navigation", root_path, class: :brand
          %ul.nav
            - Page.roots.each do |page|
              %li{ class: (:active if @page && @page.root == page) }= link_to page.name, page

    .container
      = yield

app/views/pages/_form.html.haml
= simple_form_for(@page) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :content
    = f.input :parent_id, collection: Page.order(:ancestry).map { |page| "- " * page.depth + page.name }, include_blank: true

  .form-actions
    = f.submit class: ["btn btn-primary"]

app/views/pages/_index_pages.html.haml
%ul
  - pages.each do |page, children|
    %li
      = page.name
      %span.pull-right
        = link_to "Show", page
        = link_to "Edit", edit_page_path(page)
        = link_to "Destroy", page, method: :delete
      = render "index_pages", pages: children if children.present?

app/views/pages/_submenu_pages.html.haml
%ul.nav.nav-list
  - pages.each do |page, children|
    %li{ class: (:active if current_page?(page)) }
      = link_to page.name, page
      = render "submenu_pages", pages: children if children.present?

app/views/pages/edit.html.haml
%h1 Editing page

= render 'form'

= link_to 'Show', @page
\|
= link_to 'Back', pages_path

app/views/pages/index.html.haml
%h1 Edit Pages

= render "index_pages", pages: @pages

= link_to 'New Page', new_page_path

app/views/pages/new.html.haml
%h1 New page

= render 'form'

= link_to 'Back', pages_path

app/views/pages/show.html.haml
- content_for :title, @page.name

.row
  .span4
    = render "submenu_pages", pages: @page.root.descendants.arrange if @page
  .span8
    - if @page.ancestors.any?
      %ul.breadcrumb
        - @page.ancestors.each do |page|
          %li
            = link_to page.name, page
            %span.divider /
        %li.active= @page.name
    %p#notice= notice

    %h1= @page.name
    = simple_format @page.content

    = link_to 'Edit', edit_page_path(@page)